Application skeleton impl
onixred/ticket pull request #33
Opened 2024-10-16 05:22 UTC by weateus

2024-10-16 10:13 UTC, onixred requested changes
https://habr.com/ru/companies/otus/articles/777260/ можно почитать пост

2024-10-16 10:13 UTC, onixred commented on pom.xml
> +        <license/>
эту секцию можно убрать

2024-10-16 10:13 UTC, onixred commented on pom.xml
> +        <developer/>
это тоже можно убрать

2024-10-16 10:13 UTC, onixred commented on pom.xml
> +    </scm>
тоже не нужно

2024-10-16 10:13 UTC, onixred commented on pom.xml
> +            <version>1.6.2</version>
версию вытащить в properties

2024-10-16 10:13 UTC, onixred commented on pom.xml
> +            <version>0.2.0</version>
версию вытащить в properties

2024-10-16 10:13 UTC, onixred commented on pom.xml
> +            <artifactId>mapstruct</artifactId>
мы используем в работе но можно и mapstruct
```
<dependency>
    <groupId>org.modelmapper</groupId>
    <artifactId>modelmapper</artifactId>
</dependency>
```

2024-10-16 10:13 UTC, onixred commented on pom.xml
> +                            <version>1.6.2</version>
лучше использовать свойства properties

2024-10-16 10:13 UTC, onixred commented on pom.xml
> +                            <version>0.2.0</version>
тоже использовать версию из свойств

2024-10-16 10:13 UTC, onixred commented on src/main/java/my/pet/ticket/adapter/persistence/TicketEntity.java
> +package my.pet.ticket.adapter.persistence;
можно добавить уточнение my.pet.ticket.adapter.out.persistence.entity

2024-10-16 10:13 UTC, onixred commented on src/main/java/my/pet/ticket/adapter/persistence/TicketEntityMapper.java
> +package my.pet.ticket.adapter.persistence;
можно добавить уточнение my.pet.ticket.adapter.out.persistence.mapper или  acl

2024-10-16 10:13 UTC, onixred commented on src/main/java/my/pet/ticket/adapter/persistence/TicketJpaRepository.java
> +package my.pet.ticket.adapter.persistence;
можно добавить уточнение my.pet.ticket.adapter.out.persistence

2024-10-16 10:13 UTC, onixred commented on src/main/java/my/pet/ticket/adapter/persistence/TicketRepositoryImpl.java
> +@Repository
эту аннотацию не используют в гегсоганалке

2024-10-16 10:13 UTC, onixred commented on src/main/java/my/pet/ticket/adapter/persistence/TicketRepositoryImpl.java
> +public class TicketRepositoryImpl implements TicketRepository {
лучше переименовать TicketJpaAdapter

нужен интерфейс в my.pet.ticket.application.in. 

и есть поле  private final TicketRepository ticketRepository;

2024-10-16 10:13 UTC, onixred commented on src/main/java/my/pet/ticket/adapter/web/TicketController.java
> +package my.pet.ticket.adapter.web;
тут лучше использовать пакет my.pet.ticket.adapter.in.rest;

2024-10-16 10:13 UTC, onixred commented on src/main/java/my/pet/ticket/adapter/web/TicketDto.java
> +package my.pet.ticket.adapter.web;
лучше использовать пакет my.pet.ticket.adapter.in.rest.resource

2024-10-16 10:13 UTC, onixred commented on src/main/java/my/pet/ticket/adapter/web/TicketDtoMapper.java
> +public interface TicketDtoMapper {
лучше использовать пакет my.pet.ticket.adapter.in.rest.mapper или acl

2024-10-16 10:13 UTC, onixred commented on src/main/java/my/pet/ticket/domain/Ticket.java
> +package my.pet.ticket.domain;
my.pet.ticket.application.domain или my.pet.ticket.application.model

2024-10-16 10:13 UTC, onixred commented on src/main/java/my/pet/ticket/domain/TicketService.java
> +package my.pet.ticket.domain;
my.pet.ticket.application

2024-10-16 10:13 UTC, onixred commented on src/main/java/my/pet/ticket/domain/TicketService.java
> +package my.pet.ticket.domain;
нужен интерфейс в my.pet.ticket.application.in

2024-10-16 10:13 UTC, onixred commented on src/main/java/my/pet/ticket/port/TicketRepository.java
> +public interface TicketRepository {
это кажется нужно  в my.pet.ticket.application.out

2024-10-16 10:13 UTC, onixred commented on pom.xml
> +        <license/>
https://habr.com/ru/companies/otus/articles/777260/ можно почитать тут

2024-10-17 07:30 UTC, weateus commented on pom.xml
> +        <license/>
убрал

2024-10-17 07:30 UTC, weateus commented on pom.xml
> +        <developer/>
убрал

2024-10-17 07:30 UTC, weateus commented on pom.xml
> +    </scm>
убрал

2024-10-17 07:30 UTC, weateus commented on pom.xml
> +            <version>1.6.2</version>
исправил

2024-10-17 07:30 UTC, weateus commented on pom.xml
> +            <version>0.2.0</version>
исправил

2024-10-17 07:31 UTC, weateus commented on pom.xml
> +            <artifactId>mapstruct</artifactId>
заменил

2024-10-17 07:31 UTC, weateus commented on pom.xml
> +                            <version>1.6.2</version>
исправил

2024-10-17 07:31 UTC, weateus commented on pom.xml
> +                            <version>0.2.0</version>
исправил

2024-10-17 07:32 UTC, weateus commented on src/main/java/my/pet/ticket/adapter/persistence/TicketEntity.java
> +package my.pet.ticket.adapter.persistence;
исправил

2024-10-17 07:34 UTC, weateus commented on src/main/java/my/pet/ticket/adapter/persistence/TicketEntityMapper.java
> +package my.pet.ticket.adapter.persistence;
исправил

2024-10-17 07:34 UTC, weateus commented on src/main/java/my/pet/ticket/adapter/persistence/TicketJpaRepository.java
> +package my.pet.ticket.adapter.persistence;
исправил

2024-10-17 07:34 UTC, weateus commented on src/main/java/my/pet/ticket/adapter/persistence/TicketRepositoryImpl.java
> +@Repository
исправил

2024-10-17 07:34 UTC, weateus commented on src/main/java/my/pet/ticket/adapter/persistence/TicketRepositoryImpl.java
> +public class TicketRepositoryImpl implements TicketRepository {
исправил

2024-10-17 07:35 UTC, weateus commented on src/main/java/my/pet/ticket/adapter/web/TicketController.java
> +package my.pet.ticket.adapter.web;
исправил

2024-10-17 07:36 UTC, weateus commented on src/main/java/my/pet/ticket/adapter/web/TicketDto.java
> +package my.pet.ticket.adapter.web;
исправил

2024-10-17 07:37 UTC, weateus commented on src/main/java/my/pet/ticket/adapter/web/TicketDtoMapper.java
> +public interface TicketDtoMapper {
исправил

2024-10-17 07:37 UTC, weateus commented on src/main/java/my/pet/ticket/domain/Ticket.java
> +package my.pet.ticket.domain;
исправил

2024-10-17 07:38 UTC, weateus commented on src/main/java/my/pet/ticket/port/TicketRepository.java
> +public interface TicketRepository {
исправил

2024-10-17 07:59 UTC, weateus commented on src/main/java/my/pet/ticket/domain/TicketService.java
> +package my.pet.ticket.domain;
добавил

2024-10-21 07:08 UTC, merged